#!/bin/bash
DIR="`dirname $0`"       # compute a full path name to this script
DIR=${DIR%\/}            # strip off trailing slash
DIR=${DIR/\/\/\//\/}     # reduce any initial /// to /

DBCRED="$DIR/DBCRED"
FILE_NAME="db_dump"
DEFAULT_SCHEMA="public"

echo Reading DB credentials
if [ ! -f "$DBCRED" ];
then
	echo ERROR: Missing DBCRED file: "$DBCRED"
	exit 2;
fi
echo Loading DB credentials
. $DBCRED

# parse more schemata provided as CSV into " -n schema1 -n schema2" format
# also detect whether $DEFAULT_SCHEMA is being imported and forcerecreate it if so
SCHEMA_CLAUSE=''
SCHEMA_PUBLIC_PROCESSING=0
while IFS=',' read -ra ADDR; do
	for SCHEMA in "${ADDR[@]}"; do
		SCHEMA_CLAUSE="$SCHEMA_CLAUSE -n $SCHEMA";
		if [[ $SCHEMA == $DEFAULT_SCHEMA ]]; then
			SCHEMA_PUBLIC_PROCESSING=1
		fi
	done
done <<< "$SOURCE_PG_SCHEMA"

if [ ! -f "$DIR/$FILE_NAME-$SOURCE_PG_SCHEMA.sql" ];
then
    echo Creating a dump of the source DB schemata $SOURCE_PG_SCHEMA
    PGPASSWORD=$SOURCE_PG_PASSWORD pg_dump --encoding utf8 -h $SOURCE_PG_HOST -p $SOURCE_PG_PORT -U $SOURCE_PG_USER $SCHEMA_CLAUSE -O -x \
        --exclude-table-data=b2b.application_log \
        --exclude-table-data=b2b.counseling_operation \
        --exclude-table-data=b2b.history \
        --exclude-table-data=b2b.log \
        --exclude-table-data=b2b.profile_export \
        --exclude-table-data=b2b.profile_export_pod \
        --exclude-table-data=b2b.profile_export_tmp \
        --exclude-table-data=b2b.user_ic_export \
        --exclude-table-data=b2b.users_eon_egd_bc \
        --exclude-table-data=form_service.wso_log \
        $SOURCE_PG_DATABASE > $DIR/$FILE_NAME-$SOURCE_PG_SCHEMA.sql
    EXIT_CODE=$?
    if [ $EXIT_CODE -ne 0 ]; then
	    echo ERROR: Unable to dump the DB schemata $SOURCE_PG_SCHEMA
	    exit $EXIT_CODE
    fi
else
	echo INFO: Already got fresh dump
fi

echo Deleting data from the target DB
RECREATE_PUBLIC=''
if [ $SCHEMA_PUBLIC_PROCESSING -ne 0 ]; then
	RECREATE_PUBLIC="CREATE SCHEMA $DEFAULT_SCHEMA;"
fi

PGPASSWORD=$TARGET_PG_PASSWORD psql -U $TARGET_PG_USER -h $TARGET_PG_HOST -p $TARGET_PG_PORT -d $TARGET_PG_DATABASE -c "DROP SCHEMA IF EXISTS $SOURCE_PG_SCHEMA CASCADE;$RECREATE_PUBLIC"
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
	echo ERROR: Unable to drop schemata $SOURCE_PG_SCHEMA
	exit $EXIT_CODE
fi

if [ ! -z "${TARGET_PG_GROUP_ROLE}" ]; then
    echo "SET ROLE ${TARGET_PG_GROUP_ROLE};" | cat - $DIR/$FILE_NAME-$SOURCE_PG_SCHEMA.sql > /tmp/intermediate && mv /tmp/intermediate $DIR/$FILE_NAME-$SOURCE_PG_SCHEMA.sql
fi

echo Importing the dump to the target DB
PGPASSWORD=$TARGET_PG_PASSWORD psql -U $TARGET_PG_USER -h $TARGET_PG_HOST -p $TARGET_PG_PORT -d $TARGET_PG_DATABASE < $DIR/$FILE_NAME-$SOURCE_PG_SCHEMA.sql
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
	echo ERROR: Unable to import a DB dump
fi

exit $EXIT_CODE
